import { Doctor } from "./doctorsStore";

export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Dr. Ayesha Siddiqua",
    specialty: "Cardiology",
    hospital: "National Heart Foundation Hospital",
    experience: "16 years",
    rating: 4.9,
    reviewCount: 312,
    location: "Dhaka",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    fees: "৳1500",
    about:
      "Dr. Ayesha Siddiqua is a leading cardiologist specializing in preventive cardiology and interventional procedures in Bangladesh.",
    education: [
      "MBBS - Dhaka Medical College (2006)",
      "MD Cardiology - BSMMU (2011)",
      "FACC - American College of Cardiology (2015)",
    ],
    certifications: [
      "BCPS in Cardiology",
      "BMD Council Certified",
      "Fellowship in Interventional Cardiology",
    ],
    languages: ["Bengali", "English"],
    availability: "today",
  },
  {
    id: 2,
    name: "Dr. Mahmudul Hasan",
    specialty: "General Medicine",
    hospital: "Square Hospitals Ltd.",
    experience: "12 years",
    rating: 4.7,
    reviewCount: 245,
    location: "Dhaka",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face",
    fees: "৳1200",
    about:
      "Dr. Mahmudul Hasan provides comprehensive general medicine care with a focus on chronic illness and primary health management.",
    education: [
      "MBBS - Sir Salimullah Medical College (2008)",
      "FCPS - Internal Medicine (2014)",
    ],
    certifications: ["BCPS Certified", "BMD Council Registered"],
    languages: ["Bengali", "English"],
    availability: "today",
  },
  {
    id: 3,
    name: "Dr. Sharmeen Ahmed",
    specialty: "Pediatrics",
    hospital: "Shishu Hospital",
    experience: "10 years",
    rating: 4.8,
    reviewCount: 198,
    location: "Chittagong",
    image: "https://images.unsplash.com/photo-1659353888906-adb3e0041693?w=700",
    fees: "৳1000",
    about:
      "Dr. Sharmeen Ahmed is a child specialist who brings compassionate care and expertise in child development and immunization.",
    education: [
      "MBBS - Chittagong Medical College (2010)",
      "MD Pediatrics - BSMMU (2015)",
    ],
    certifications: ["BCPS Certified Pediatrician"],
    languages: ["Bengali", "English"],
    availability: "today",
  },
  {
    id: 4,
    name: "Dr. Farhan Kabir",
    specialty: "Orthopedics",
    hospital: "Ibn Sina Hospital",
    experience: "14 years",
    rating: 4.6,
    reviewCount: 180,
    location: "Sylhet",
    image:
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&crop=face",
    fees: "৳1800",
    about:
      "Expert in trauma and joint replacement, Dr. Kabir is a trusted orthopedic surgeon known for successful sports injury treatments.",
    education: [
      "MBBS - Sylhet MAG Osmani Medical College (2007)",
      "MS Orthopedics - BSMMU (2013)",
    ],
    certifications: ["BCPS Orthopedic Surgery"],
    languages: ["Bengali", "English"],
    availability: "today",
  },
  {
    id: 5,
    name: "Dr. Nusrat Jahan",
    specialty: "Dermatology",
    hospital: "Evercare Hospital",
    experience: "9 years",
    rating: 4.9,
    reviewCount: 160,
    location: "Dhaka",
    image:
      "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&h=400&fit=crop&crop=face",
    fees: "৳1300",
    about:
      "Dr. Nusrat Jahan specializes in aesthetic dermatology, laser therapy, and skin disease treatment with modern techniques.",
    education: ["MBBS - Dhaka Medical College (2012)", "DDV - BIRDEM (2017)"],
    certifications: ["BMD Certified Dermatologist"],
    languages: ["Bengali", "English"],
    availability: "today",
  },
  {
    id: 6,
    name: "Dr. Tanvir Rahman",
    specialty: "Neurology",
    hospital: "Bangabandhu Sheikh Mujib Medical University (BSMMU)",
    experience: "18 years",
    rating: 4.9,
    reviewCount: 210,
    location: "Dhaka",
    image:
      "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face",
    fees: "৳2000",
    about:
      "Renowned for treating neurological disorders and stroke care, Dr. Rahman is a top neurologist with international fellowships.",
    education: [
      "MBBS - Rajshahi Medical College (2005)",
      "MD Neurology - BSMMU (2010)",
      "Fellowship - King’s College London (2014)",
    ],
    certifications: ["Board Certified in Neurology", "Member of BAN and WFN"],
    languages: ["Bengali", "English"],
    availability: "today",
  },
];

export const slots = [
  { doctorId: 1, date: "2025-06-13", times: ["09:00 AM", "10:30 AM"] },
  { doctorId: 2, date: "2025-06-13", times: ["02:00 PM", "04:00 PM"] },
  { doctorId: 3, date: "2025-06-14", times: ["08:30 AM", "10:00 AM"] },
  { doctorId: 4, date: "2025-06-14", times: ["10:30 AM", "12:30 PM"] },
  { doctorId: 5, date: "2025-06-15", times: ["01:00 PM", "03:00 PM"] },
  { doctorId: 6, date: "2025-06-15", times: ["10:00 AM", "12:00 PM"] },
  { doctorId: 1, date: "2025-06-16", times: ["09:00 AM", "11:00 AM"] },
  { doctorId: 2, date: "2025-06-16", times: ["03:00 PM", "05:00 PM"] },
  { doctorId: 3, date: "2025-06-17", times: ["10:00 AM", "12:00 PM"] },
];

export const reviews = [
  // Doctor 1: Dr. Ayesha Siddiqua
  {
    doctorId: 1,
    patient: "Sadia R.",
    rating: 5,
    comment:
      "She listened carefully and explained everything in detail. Highly professional.",
    date: "2025-06-01",
  },
  {
    doctorId: 1,
    patient: "Arifa N.",
    rating: 5,
    comment: "Provided excellent treatment and follow-up advice.",
    date: "2025-06-11",
  },
  {
    doctorId: 1,
    patient: "Maliha K.",
    rating: 4,
    comment: "Really listens to your problems patiently.",
    date: "2025-06-11",
  },
  {
    doctorId: 1,
    patient: "Hasan E.",
    rating: 5,
    comment: "Clinic was well organized and time-efficient.",
    date: "2025-06-02",
  },
  {
    doctorId: 1,
    patient: "Maliha K.",
    rating: 5,
    comment: "Clinic was well organized and time-efficient.",
    date: "2025-06-01",
  },
  {
    doctorId: 1,
    patient: "Hasan E.",
    rating: 5,
    comment: "Highly professional and friendly.",
    date: "2025-06-06",
  },
  {
    doctorId: 1,
    patient: "Tania A.",
    rating: 4,
    comment: "Explained everything with great detail and care.",
    date: "2025-06-08",
  },
  {
    doctorId: 1,
    patient: "Rubel M.",
    rating: 5,
    comment: "Great experience, felt very comfortable.",
    date: "2025-06-09",
  },
  {
    doctorId: 1,
    patient: "Rafiq K.",
    rating: 5,
    comment: "Made me feel at ease during the entire visit.",
    date: "2025-06-10",
  },
  {
    doctorId: 1,
    patient: "Sadia R.",
    rating: 5,
    comment: "Very skilled and courteous.",
    date: "2025-06-12",
  },

  // Doctor 2: Dr. Mahmudul Hasan
  {
    doctorId: 2,
    patient: "Mehedi H.",
    rating: 5,
    comment: "Very friendly and accurate in diagnosis. Highly recommended.",
    date: "2025-06-02",
  },
  {
    doctorId: 2,
    patient: "Arifa N.",
    rating: 5,
    comment: "Explained everything with great detail and care.",
    date: "2025-06-11",
  },
  {
    doctorId: 2,
    patient: "Tahmina B.",
    rating: 4,
    comment: "Really listens to your problems patiently.",
    date: "2025-06-03",
  },
  {
    doctorId: 2,
    patient: "Javed U.",
    rating: 5,
    comment: "Clinic was well organized and time-efficient.",
    date: "2025-06-06",
  },
  {
    doctorId: 2,
    patient: "Shafiq A.",
    rating: 5,
    comment: "Very kind and helpful throughout the consultation.",
    date: "2025-06-08",
  },
  {
    doctorId: 2,
    patient: "Tania A.",
    rating: 4,
    comment: "Great experience, felt very comfortable.",
    date: "2025-06-10",
  },
  {
    doctorId: 2,
    patient: "Nazmul I.",
    rating: 5,
    comment: "Helped me through recovery very well.",
    date: "2025-06-11",
  },
  {
    doctorId: 2,
    patient: "Hasan E.",
    rating: 5,
    comment: "Very skilled and courteous.",
    date: "2025-06-12",
  },
  {
    doctorId: 2,
    patient: "Shanta D.",
    rating: 5,
    comment: "One of the top specialists in Bangladesh.",
    date: "2025-06-04",
  },
  {
    doctorId: 2,
    patient: "Rubel M.",
    rating: 4,
    comment: "Highly professional and friendly.",
    date: "2025-06-07",
  },

  // Doctor 3: Dr. Sharmeen Ahmed
  {
    doctorId: 3,
    patient: "Tania A.",
    rating: 5,
    comment: "Great experience for my child. She’s very kind and approachable.",
    date: "2025-06-03",
  },
  {
    doctorId: 3,
    patient: "Nazmul I.",
    rating: 5,
    comment: "Explained everything with great detail and care.",
    date: "2025-06-01",
  },
  {
    doctorId: 3,
    patient: "Rubel M.",
    rating: 4,
    comment: "Very kind and helpful throughout the consultation.",
    date: "2025-06-02",
  },
  {
    doctorId: 3,
    patient: "Tahmina B.",
    rating: 5,
    comment: "Clinic was well organized and time-efficient.",
    date: "2025-06-04",
  },
  {
    doctorId: 3,
    patient: "Arifa N.",
    rating: 5,
    comment: "Really listens to your problems patiently.",
    date: "2025-06-06",
  },
  {
    doctorId: 3,
    patient: "Lamia Z.",
    rating: 5,
    comment: "Helped me through recovery very well.",
    date: "2025-06-07",
  },
  {
    doctorId: 3,
    patient: "Farhan S.",
    rating: 5,
    comment: "Made me feel at ease during the entire visit.",
    date: "2025-06-08",
  },
  {
    doctorId: 3,
    patient: "Javed U.",
    rating: 4,
    comment: "One of the top specialists in Bangladesh.",
    date: "2025-06-10",
  },
  {
    doctorId: 3,
    patient: "Shafiq A.",
    rating: 5,
    comment: "Very skilled and courteous.",
    date: "2025-06-11",
  },
  {
    doctorId: 3,
    patient: "Mehedi H.",
    rating: 5,
    comment: "Great experience, felt very comfortable.",
    date: "2025-06-12",
  },

  // Doctor 4: Dr. Farhan Kabir
  {
    doctorId: 4,
    patient: "Rafiq K.",
    rating: 4,
    comment: "Helped me recover from a shoulder injury. Very satisfied.",
    date: "2025-06-01",
  },
  {
    doctorId: 4,
    patient: "Maliha K.",
    rating: 5,
    comment: "Clinic was well organized and time-efficient.",
    date: "2025-06-02",
  },
  {
    doctorId: 4,
    patient: "Lamia Z.",
    rating: 4,
    comment: "Great experience, felt very comfortable.",
    date: "2025-06-03",
  },
  {
    doctorId: 4,
    patient: "Shanta D.",
    rating: 5,
    comment: "One of the top specialists in Bangladesh.",
    date: "2025-06-04",
  },
  {
    doctorId: 4,
    patient: "Farhan S.",
    rating: 5,
    comment: "Made me feel at ease during the entire visit.",
    date: "2025-06-06",
  },
  {
    doctorId: 4,
    patient: "Javed U.",
    rating: 5,
    comment: "Very kind and helpful throughout the consultation.",
    date: "2025-06-07",
  },
  {
    doctorId: 4,
    patient: "Sadia R.",
    rating: 5,
    comment: "Explained everything with great detail and care.",
    date: "2025-06-08",
  },
  {
    doctorId: 4,
    patient: "Rubel M.",
    rating: 5,
    comment: "Helped me through recovery very well.",
    date: "2025-06-09",
  },
  {
    doctorId: 4,
    patient: "Hasan E.",
    rating: 5,
    comment: "Very skilled and courteous.",
    date: "2025-06-10",
  },
  {
    doctorId: 4,
    patient: "Nazmul I.",
    rating: 4,
    comment: "Highly professional and friendly.",
    date: "2025-06-12",
  },

  // Doctor 5: Dr. Nusrat Jahan
  {
    doctorId: 5,
    patient: "Lamia Z.",
    rating: 5,
    comment: "My acne condition improved significantly. She’s very attentive.",
    date: "2025-06-05",
  },
  {
    doctorId: 5,
    patient: "Nazmul I.",
    rating: 4,
    comment: "Made me feel at ease during the entire visit.",
    date: "2025-06-06",
  },
  {
    doctorId: 5,
    patient: "Arifa N.",
    rating: 5,
    comment: "Clinic was well organized and time-efficient.",
    date: "2025-06-07",
  },
  {
    doctorId: 5,
    patient: "Tania A.",
    rating: 5,
    comment: "One of the best doctors I've visited in Dhaka.",
    date: "2025-06-08",
  },
  {
    doctorId: 5,
    patient: "Sadia R.",
    rating: 4,
    comment: "Helped me through recovery very well.",
    date: "2025-06-09",
  },
  {
    doctorId: 5,
    patient: "Farhan S.",
    rating: 5,
    comment: "Explained everything with great detail and care.",
    date: "2025-06-10",
  },
  {
    doctorId: 5,
    patient: "Javed U.",
    rating: 5,
    comment: "Very kind and helpful throughout the consultation.",
    date: "2025-06-11",
  },
  {
    doctorId: 5,
    patient: "Rubel M.",
    rating: 5,
    comment: "Great experience, felt very comfortable.",
    date: "2025-06-12",
  },
  {
    doctorId: 5,
    patient: "Maliha K.",
    rating: 5,
    comment: "Very skilled and courteous.",
    date: "2025-06-01",
  },
  {
    doctorId: 5,
    patient: "Shafiq A.",
    rating: 5,
    comment: "Highly professional and friendly.",
    date: "2025-06-02",
  },

  // Doctor 6: Dr. Tanvir Rahman
  {
    doctorId: 6,
    patient: "Farhan S.",
    rating: 5,
    comment:
      "Best neurologist I’ve visited. Very thorough and expert in his field.",
    date: "2025-06-06",
  },
  {
    doctorId: 6,
    patient: "Nazmul I.",
    rating: 5,
    comment: "Explained everything with great detail and care.",
    date: "2025-06-01",
  },
  {
    doctorId: 6,
    patient: "Rubel M.",
    rating: 4,
    comment: "Made me feel at ease during the entire visit.",
    date: "2025-06-02",
  },
  {
    doctorId: 6,
    patient: "Tania A.",
    rating: 5,
    comment: "Very skilled and courteous.",
    date: "2025-06-03",
  },
  {
    doctorId: 6,
    patient: "Lamia Z.",
    rating: 5,
    comment: "One of the top specialists in Bangladesh.",
    date: "2025-06-04",
  },
  {
    doctorId: 6,
    patient: "Arifa N.",
    rating: 5,
    comment: "Great experience, felt very comfortable.",
    date: "2025-06-05",
  },
  {
    doctorId: 6,
    patient: "Sadia R.",
    rating: 5,
    comment: "Clinic was well organized and time-efficient.",
    date: "2025-06-07",
  },
  {
    doctorId: 6,
    patient: "Javed U.",
    rating: 4,
    comment: "Highly professional and friendly.",
    date: "2025-06-08",
  },
  {
    doctorId: 6,
    patient: "Hasan E.",
    rating: 5,
    comment: "Very kind and helpful throughout the consultation.",
    date: "2025-06-09",
  },
  {
    doctorId: 6,
    patient: "Shafiq A.",
    rating: 5,
    comment: "Explained everything with great detail and care.",
    date: "2025-06-10",
  },
];
