import { Doctor } from "./doctorsStore";

export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialty: "Cardiology",
    hospital: "City General Hospital",
    experience: "15 years",
    rating: 4.9,
    reviewCount: 234,
    location: "New York",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    fees: "$150",
    about:
      "Dr. Sarah Johnson is a board-certified cardiologist with over 15 years of experience. She specializes in preventive cardiology and cardiac catheterization.",
    education: [
      "MD - Harvard Medical School (2008)",
      "Residency - Johns Hopkins Hospital (2012)",
      "Fellowship - Mayo Clinic (2014)",
    ],
    certifications: [
      "Board Certified in Cardiology",
      "Advanced Cardiac Life Support (ACLS)",
      "Interventional Cardiology Certification",
    ],
    languages: ["English", "Spanish"],
    availability: "today",
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    specialty: "General Medicine",
    hospital: "Metro Medical Center",
    experience: "12 years",
    rating: 4.8,
    reviewCount: 190,
    location: "Los Angeles",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face",
    fees: "$120",
    about:
      "Dr. Michael Chen has a broad range of expertise in internal and general medicine. He is known for his holistic approach to diagnosis and care.",
    education: [
      "MD - Stanford School of Medicine (2010)",
      "Residency - UCLA Medical Center (2014)",
    ],
    certifications: ["Board Certified in Internal Medicine"],
    languages: ["English", "Mandarin"],
    availability: "today",
  },
  {
    id: 3,
    name: "Dr. Emily Rodriguez",
    specialty: "Pediatrics",
    hospital: "Children's Health Center",
    experience: "10 years",
    rating: 4.9,
    reviewCount: 180,
    location: "Chicago",
    image:
      "https://images.unsplash.com/photo-1594824919066-4dac3dde0583?w=400&h=400&fit=crop&crop=face",
    fees: "$100",
    about:
      "Dr. Emily Rodriguez is passionate about child health and development. She offers compassionate care tailored to young patients and their families.",
    education: [
      "MD - University of Chicago (2012)",
      "Residency - Lurie Children’s Hospital (2016)",
    ],
    certifications: ["Board Certified in Pediatrics"],
    languages: ["English", "Spanish"],
    availability: "today",
  },
  {
    id: 4,
    name: "Dr. James Wilson",
    specialty: "Orthopedics",
    hospital: "Sports Medicine Institute",
    experience: "18 years",
    rating: 4.7,
    reviewCount: 205,
    location: "Houston",
    image:
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&crop=face",
    fees: "$200",
    about:
      "Dr. James Wilson is a seasoned orthopedic surgeon with a focus on sports injuries, joint replacement, and musculoskeletal health.",
    education: [
      "MD - Baylor College of Medicine (2005)",
      "Residency - Houston Methodist (2009)",
    ],
    certifications: ["Board Certified in Orthopedic Surgery"],
    languages: ["English"],
    availability: "today",
  },
  {
    id: 5,
    name: "Dr. Lisa Thompson",
    specialty: "Dermatology",
    hospital: "Skin Care Clinic",
    experience: "8 years",
    rating: 4.8,
    reviewCount: 150,
    location: "Miami",
    image:
      "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&h=400&fit=crop&crop=face",
    fees: "$130",
    about:
      "Dr. Lisa Thompson provides advanced dermatological care, including acne treatment, skin screenings, and cosmetic dermatology.",
    education: [
      "MD - University of Miami (2015)",
      "Residency - Jackson Memorial Hospital (2019)",
    ],
    certifications: ["Board Certified in Dermatology"],
    languages: ["English", "French"],
    availability: "today",
  },
  {
    id: 6,
    name: "Dr. Robert Kim",
    specialty: "Neurology",
    hospital: "Brain Health Center",
    experience: "20 years",
    rating: 4.9,
    reviewCount: 220,
    location: "Seattle",
    image:
      "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face",
    fees: "$250",
    about:
      "Dr. Robert Kim is a highly respected neurologist specializing in brain disorders, migraines, and neurodegenerative conditions.",
    education: [
      "MD - University of Washington (2003)",
      "Residency - Swedish Medical Center (2007)",
      "Fellowship - Cleveland Clinic (2009)",
    ],
    certifications: [
      "Board Certified in Neurology",
      "Neurophysiology Certification",
    ],
    languages: ["English", "Korean"],
    availability: "today",
  },
];
export const slots = [
  { doctorId: 1, date: "2024-06-13", times: ["09:00 AM", "10:30 AM"] },
  { doctorId: 1, date: "2024-06-14", times: ["02:00 PM", "03:30 PM"] },
  { doctorId: 2, date: "2024-06-14", times: ["09:30 AM", "11:00 AM"] },
  { doctorId: 2, date: "2024-06-15", times: ["10:00 AM", "12:00 PM"] },
  { doctorId: 3, date: "2024-06-13", times: ["08:30 AM", "10:00 AM"] },
  { doctorId: 3, date: "2024-06-14", times: ["09:00 AM", "03:00 PM"] },
  { doctorId: 4, date: "2024-06-16", times: ["10:00 AM", "12:00 PM"] },
  { doctorId: 4, date: "2024-06-17", times: ["01:30 PM", "03:30 PM"] },
  { doctorId: 5, date: "2024-06-13", times: ["09:00 AM", "11:00 AM"] },
  { doctorId: 5, date: "2024-06-14", times: ["01:00 PM", "04:00 PM"] },
  { doctorId: 6, date: "2024-06-14", times: ["10:30 AM", "01:00 PM"] },
  { doctorId: 6, date: "2024-06-15", times: ["03:30 PM", "05:00 PM"] },
  { doctorId: 1, date: "2024-06-15", times: ["08:00 AM", "10:00 AM"] },
  { doctorId: 2, date: "2024-06-16", times: ["02:00 PM", "04:00 PM"] },
  { doctorId: 3, date: "2024-06-15", times: ["01:00 PM", "02:30 PM"] },
];
export const reviews = [
  {
    doctorId: 1,
    patient: "John D.",
    rating: 5,
    comment: "Excellent doctor! Very thorough examination.",
    date: "2024-05-15",
  },
  {
    doctorId: 2,
    patient: "Alice T.",
    rating: 5,
    comment: "Very friendly and explains everything clearly.",
    date: "2024-05-12",
  },
  {
    doctorId: 3,
    patient: "Carla M.",
    rating: 5,
    comment: "Great with kids and very knowledgeable.",
    date: "2024-05-14",
  },
  {
    doctorId: 4,
    patient: "Mark R.",
    rating: 4,
    comment: "Helped me recover from a knee injury.",
    date: "2024-05-01",
  },
  {
    doctorId: 5,
    patient: "Sophie L.",
    rating: 5,
    comment: "My skin has never been better.",
    date: "2024-05-09",
  },
  {
    doctorId: 6,
    patient: "Henry P.",
    rating: 5,
    comment: "Diagnosed a condition others missed.",
    date: "2024-05-08",
  },
  {
    doctorId: 3,
    patient: "Tom B.",
    rating: 4,
    comment: "Helpful advice and good rapport.",
    date: "2024-05-11",
  },
  {
    doctorId: 2,
    patient: "Natalie K.",
    rating: 5,
    comment: "Efficient and caring doctor.",
    date: "2024-05-07",
  },
  {
    doctorId: 1,
    patient: "Greg N.",
    rating: 5,
    comment: "Trustworthy and knowledgeable.",
    date: "2024-05-10",
  },
];
